---
# tasks file for /etc/ansible/roles/role3
- name: Ensure firewalld is installed
  ansible.builtin.dnf:
    name: "{{var_package}}"
    state: present

- name: Ensure firewalld is running
  ansible.builtin.service:
    name: "{{var_package}}"
    state: started
    enabled: true

- name: Create zone
  ansible.posix.firewalld:
    zone: "{{ var_zone }}"
    state: present
    permanent: true

- name: Allow samba and ssh on specific port
  ansible.posix.firewalld:
    zone: "{{ var_zone }}"
    service: "{{ var_service1 }}"
    permanent: true
    state: enabled

- name: Allow samba and ssh on specific port
  ansible.posix.firewalld:
    zone: "{{ var_zone }}"
    service: "{{ var_service2 }}"
    permanent: true
    state: enabled


- name: Add port to firewall zone
  ansible.posix.firewalld:
    zone: "{{ var_zone }}"
    port: "{{ var_port }}"
    permanent: true
    state: enabled

- name: Set zone to reject
  ansible.posix.firewalld:
    zone: "{{ var_zone }}"
    state: present
    permanent: true
    target: '%%REJECT%%'
  notify: restart firewalld

